FROM nginx
COPY /web /usr/share/nginx/html
RUN rm /usr/share/nginx/html/index.html
RUN rm etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
